name: CI
on:
  push:
  - main
jobs:
  build:
    name: Say Hello
    runs-on: ubuntu-latest
    steps:
    - name: Checkout (optional for empty repo)
      uses: actions/checkout@v4
    - name: Say hi
      run: echo "Hello from GitHub Actions!"
